### PR TITLE
Cross Platform way to Determine Console Size

### PR DESCRIPTION
**Pull request by minchinweb**
Tested on Windows. Now `fabulous-demo` will run!

### CODE REVIEW

**Comment by minchinweb** [comment]
There, now the tests pass on Travis-CI too!

**Comment by jart** [comment]
Thanks for submitting this. I'd rather not introduce upstream dependencies. It might be better if we implement something along the lines of termios in combination with inband probing like `\e7\e[9979;9979H\e[6n\e8 → \e[𝑦;𝑥R`

**Comment by minchinweb** [comment]
@jart Are you still supporting Python 2.7 and 3.2?

Starting with Python 3.3, the required function was added to the standard library, and thus does not require any upstream dependency...

**Comment by jart** [comment]
I'm happy to bump up to Python 3.3 but I definitely want to keep supporting Python 2.7. Perhaps we could simply keep doing what we're doing for 2.7 and have the update apply only to Python 3.3+ users?

**Pull request closed without merging**
